import type {
  User,
  Building,
  Unit,
  Amenity,
  Meter,
  RentalRequest,
  AmenityBooking,
  Contract,
  Payment,
} from "./types";
import prop1 from "@/assets/prop1.jpg";
import prop2 from "@/assets/prop2.jpg";
import prop3 from "@/assets/prop3.jpg";
import prop4 from "@/assets/prop4.jpg";
import prop5 from "@/assets/prop5.jpg";
import prop6 from "@/assets/prop6.jpg";

export const seedUsers: User[] = [
  {
    id: "u1",
    name: "Ana Admin",
    email: "admin@estate.com",
    password: "admin123",
    role: "admin",
    createdAt: "2024-01-10",
  },
  {
    id: "u2",
    name: "Carlos Propietario",
    email: "owner@estate.com",
    password: "owner123",
    role: "owner",
    createdAt: "2024-02-15",
  },
  {
    id: "u3",
    name: "María Inquilina",
    email: "tenant@estate.com",
    password: "tenant123",
    role: "tenant",
    createdAt: "2024-03-20",
  },
  {
    id: "u4",
    name: "Lucía Rivera",
    email: "lucia@estate.com",
    password: "123456",
    role: "tenant",
    createdAt: "2024-04-01",
  },
];

export const seedBuildings: Building[] = [
  {
    id: "b1",
    name: "Torres del Sol",
    address: "Av. Principal 123",
    city: "San Jose",
    ownerId: "u2",
    amenityIds: ["a1", "a2", "a3"],
    description:
      "Complejo residencial moderno con piscina en azotea, gimnasio equipado y terraza panorámica. Excelente conexión con transporte público.",
    images: [prop1, prop3, prop6],
  },
  {
    id: "b2",
    name: "Residencial Oasis",
    address: "Calle Verde 45",
    city: "Cartago",
    ownerId: "u2",
    amenityIds: ["a4"],
    description: "Residencial familiar con amplias zonas verdes y salón de eventos.",
    images: [prop5, prop2],
  },
  {
    id: "b3",
    name: "Edificio Sol y Mar",
    address: "Calle Marítima 88",
    city: "Heredia",
    ownerId: "u2",
    amenityIds: [],
    description: "Edificio moderno a pocos minutos de la playa.",
    images: [prop6, prop4],
  },
  {
    id: "b4",
    name: "Plaza Sol Studios",
    address: "Plaza Sol 5",
    city: "Alajuela",
    ownerId: "u2",
    amenityIds: [],
    description: "Estudios urbanos en pleno centro, ideales para profesionales.",
    images: [prop2, prop1],
  },
  {
    id: "b5",
    name: "Reyes Residencial",
    address: "Av. Reyes 22",
    city: "Cartago",
    ownerId: "u2",
    amenityIds: [],
    description: "Apartamentos renovados con acabados de diseño.",
    images: [prop4, prop3],
  },
];

export const seedAmenities: Amenity[] = [
  {
    id: "a1",
    name: "Piscina",
    icon: "🏊",
    buildingId: "b1",
    bookable: true,
    description: "Piscina climatizada en azotea con tumbonas y vista panorámica.",
    capacity: 8,
    photoUrl: undefined,
    schedule: {
      days: ["mon", "tue", "wed", "thu", "fri", "sat", "sun"],
      openTime: "08:00",
      closeTime: "20:00",
      slotDurationMinutes: 60,
    },
  },
  {
    id: "a2",
    name: "Gimnasio",
    icon: "🏋️",
    buildingId: "b1",
    bookable: true,
    description: "Gimnasio equipado con cardio, peso libre y zona funcional.",
    capacity: 6,
    photoUrl: undefined,
    schedule: {
      days: ["mon", "tue", "wed", "thu", "fri", "sat"],
      openTime: "06:00",
      closeTime: "22:00",
      slotDurationMinutes: 60,
    },
  },
  { id: "a3", name: "Terraza", icon: "🌇", buildingId: "b1", bookable: true, photoUrl: undefined },
  { id: "a4", name: "Salón eventos", icon: "🎉", buildingId: "b2", bookable: true, photoUrl: undefined },
];

export const seedUnits: Unit[] = [
  {
    id: "un1",
    buildingId: "b1",
    ownerId: "u2",
    number: "3A",
    title: "Loft luminoso en el centro",
    description:
      "Espectacular loft con grandes ventanales, suelo de madera y mucha luz natural. Cerca de transporte y restaurantes.",
    type: "apartment",
    images: [prop1, prop2, prop4],
    bedrooms: 2,
    bathrooms: 1,
    area: 78,
    rent: 1450,
    status: "rented",
    tenantId: "u3",
    featured: true,
  },
  {
    id: "un2",
    buildingId: "b1",
    ownerId: "u2",
    number: "8B",
    title: "Apartamento con piscina y vistas",
    description: "Vivienda moderna con acceso a piscina en azotea y vistas a la ciudad.",
    type: "apartment",
    images: [prop3, prop1, prop6],
    bedrooms: 3,
    bathrooms: 2,
    area: 105,
    rent: 1850,
    status: "available",
    featured: true,
  },
  {
    id: "un3",
    buildingId: "b2",
    ownerId: "u2",
    number: "Casa 1",
    title: "Casita con jardín en zona tranquila",
    description: "Casa encantadora con jardín privado, ideal para familias o teletrabajo.",
    type: "house",
    images: [prop5, prop2, prop4],
    bedrooms: 3,
    bathrooms: 2,
    area: 120,
    rent: 1650,
    status: "available",
  },
  {
    id: "un4",
    buildingId: "b4",
    ownerId: "u2",
    number: "1C",
    title: "Estudio acogedor",
    description: "Estudio compacto y bien aprovechado, perfecto para estudiantes o profesionales.",
    type: "studio",
    images: [prop2, prop4],
    bedrooms: 1,
    bathrooms: 1,
    area: 35,
    rent: 850,
    status: "available",
  },
  {
    id: "un5",
    buildingId: "b3",
    ownerId: "u2",
    number: "4A",
    title: "Apartamento moderno con balcón",
    description: "Diseño contemporáneo, cocina integrada y balcón con vistas.",
    type: "apartment",
    images: [prop6, prop1, prop3],
    bedrooms: 2,
    bathrooms: 2,
    area: 82,
    rent: 1250,
    status: "available",
    featured: true,
  },
  {
    id: "un6",
    buildingId: "b5",
    ownerId: "u2",
    number: "2B",
    title: "Cocina de diseño y amplios espacios",
    description: "Vivienda renovada con cocina de mármol y mucha luminosidad.",
    type: "apartment",
    images: [prop4, prop1, prop2],
    bedrooms: 2,
    bathrooms: 1,
    area: 70,
    rent: 1100,
    status: "available",
  },
];

export const seedMeters: Meter[] = [
  { id: "m1", unitId: "un1", type: "water", reading: 230, date: "2025-03-01" },
  { id: "m2", unitId: "un1", type: "electricity", reading: 1240, date: "2025-03-01" },
];

export const seedRequests: RentalRequest[] = [
  {
    id: "r1",
    unitId: "un2",
    tenantId: "u4",
    ownerId: "u2",
    phone: "+34 612 345 678",
    message: "Hola, me interesa mucho el apartamento. ¿Podemos visitarlo?",
    status: "pending",
    createdAt: "2025-04-10",
  },
];

export const seedBookings: AmenityBooking[] = [
  {
    id: "ab1",
    amenityId: "a1",
    tenantId: "u3",
    ownerId: "u2",
    date: "2025-04-25",
    startTime: "18:00",
    endTime: "19:00",
    status: "pending",
  },
];

export const seedContracts: Contract[] = [
  {
    id: "c1",
    unitId: "un1",
    tenantId: "u3",
    ownerId: "u2",
    startDate: "2024-09-01",
    endDate: "2025-08-31",
    monthlyRent: 1450,
    deposit: 2900,
    status: "active",
  },
];

export const seedPayments: Payment[] = [
  {
    id: "pay1",
    contractId: "c1",
    tenantId: "u3",
    month: "2025-01",
    amount: 1450,
    utilities: 95,
    status: "paid",
    paidAt: "2025-01-05",
  },
  {
    id: "pay2",
    contractId: "c1",
    tenantId: "u3",
    month: "2025-02",
    amount: 1450,
    utilities: 110,
    status: "paid",
    paidAt: "2025-02-04",
  },
  {
    id: "pay3",
    contractId: "c1",
    tenantId: "u3",
    month: "2025-03",
    amount: 1450,
    utilities: 88,
    status: "paid",
    paidAt: "2025-03-06",
  },
  {
    id: "pay4",
    contractId: "c1",
    tenantId: "u3",
    month: "2025-04",
    amount: 1450,
    utilities: 102,
    status: "pending",
  },
];
